### ISSUE TITLE
Harvester hoe throws an error when right-click on a grass block

### ISSUE THREAD

**Issue by CayeOficial** [BG-Software-LLC/WildTools#108]
### Minecraft's Version

1.16 airplane

### Plugin's Version

![image](https://user-images.githubusercontent.com/73038322/169685526-e715b3c7-dd1b-4b48-838d-d7251f406499.png)

### Describe the bug

If you have an harvester hoe, then you right-click a grass block, it converts into a farmland but throws this error:
[08:18:28 WARN]: java.lang.IllegalArgumentException: object is not an instance of declaring class
[08:18:28 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:18:28 WARN]:        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
[08:18:28 WARN]:        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:18:28 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
[08:18:28 WARN]:        at com.bgsoftware.common.reflection.ReflectMethod.invokeWithDef(ReflectMethod.java:71)
[08:18:28 WARN]:        at com.bgsoftware.common.reflection.ReflectMethod.invoke(ReflectMethod.java:63)
[08:18:28 WARN]:        at com.bgsoftware.wildtools.nms.NMSAdapter_v1_16_R3.setBlockFast(NMSAdapter_v1_16_R3.java:292)
[08:18:28 WARN]:        at com.bgsoftware.wildtools.utils.blocks.BlocksController.updateSession(BlocksController.java:58)
[08:18:28 WARN]:        at com.bgsoftware.wildtools.objects.tools.WHarvesterTool.handleUse(WHarvesterTool.java:265)
[08:18:28 WARN]:        at com.bgsoftware.wildtools.objects.tools.WHarvesterTool.onBlockInteract(WHarvesterTool.java:133)
[08:18:28 WARN]:        at com.bgsoftware.wildtools.listeners.BlocksListener.onBlockInteract(BlocksListener.java:135)
[08:18:28 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor853.execute(Unknown Source)
[08:18:28 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[08:18:28 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[08:18:28 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[08:18:28 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[08:18:28 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:549)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:532)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1796)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:32)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:10)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1330)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1323)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1299)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1143)
[08:18:28 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292)
[08:18:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)

### To Reproduce

Get a harvester hoe
Right click grass
See console

### Additional Information

Using java 16

**Comment by OmerBenGera** [comment]
Hey, I can't replicate the issue on Paper, and it seems like Airplane stopped their development (their website is not responding)

Mind trying it on Paper, let me know if it still happens.

**Comment by CayeOficial** [comment]
I've tried on a fresh server, it only happens when its on a superiorskyblock2 island

**Comment by CayeOficial** [comment]
Pickaxes also throws the same error when mining on a superiorskyblock2 island

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
