### ISSUE TITLE
Could not pass event PlayerInteractEvent

### ISSUE THREAD

**Issue by LiritoMC** [BG-Software-LLC/WildTools#120]
### Minecraft's Version

Paper v1-8_R3 (1.8.8)

### Plugin's Version

v2.13 - v2.13.0.68

### Describe the bug

I tested on crafting tool, if you right click with your wildtool in to any block that is not chest you will get a console error (Check Additional Information)

### To Reproduce

Right Click in to any block that is not chest with your wildtool in your hand. (Tested on MC 1.8.8)

### Additional Information

[ERROR] Could not pass event PlayerInteractEvent to WildTools v2.13.0.68

org.bukkit.event.EventException: null

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-PaperSpigot-"acaf625c"]

at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[server.jar:git-PaperSpigot-"acaf625c"]

at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-PaperSpigot-"acaf625c"]

at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) ~[server.jar:git-PaperSpigot-"acaf625c"]

at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) ~[server.jar:git-PaperSpigot-"acaf625c"]

at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) ~[server.jar:git-PaperSpigot-"acaf625c"]

at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:472) ~[server.jar:git-PaperSpigot-"acaf625c"]

at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:763) ~[server.jar:git-PaperSpigot-"acaf625c"]

at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) ~[server.jar:git-PaperSpigot-"acaf625c"]

at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[server.jar:git-PaperSpigot-"acaf625c"]

at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[server.jar:git-PaperSpigot-"acaf625c"]

at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_212]

at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_212]

at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[server.jar:git-PaperSpigot-"acaf625c"]

at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:741) ~[server.jar:git-PaperSpigot-"acaf625c"]

at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:366) ~[server.jar:git-PaperSpigot-"acaf625c"]

at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:680) ~[server.jar:git-PaperSpigot-"acaf625c"]

at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:583) ~[server.jar:git-PaperSpigot-"acaf625c"]

at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_212]

Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_8_R3.block.CraftBlockState cannot be cast to org.bukkit.inventory.InventoryHolder

at com.bgsoftware.wildtools.objects.tools.WCraftingTool.onBlockInteract(WCraftingTool.java:50) ~[?:?]

at com.bgsoftware.wildtools.listeners.BlocksListener.onBlockInteract(BlocksListener.java:135) ~[?:?]

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]

at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]

at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[server.jar:git-PaperSpigot-"acaf625c"]

... 18 more

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
