### ISSUE TITLE
Building tool: not removing blocks from inventory

### ISSUE THREAD

**Issue by J4im3x0** [BG-Software-LLC/WildTools#153]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-69 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 19a70d2 on HEAD)

### Plugin's Version

WildTools version 2023.1

### Describe the bug

When you try to build using wand you will get an error in console (and the blocks aint going to be removed from the inventory)

### To Reproduce

Try to build using wand you will get an error in console (and the blocks aint going to be removed from the inventory)

### Additional Information

[18:13:22 ERROR]: Could not pass event PlayerInteractEvent to WildTools v2023.1
java.lang.NoSuchMethodError: 'net.minecraft.world.level.chunk.Chunk org.bukkit.craftbukkit.v1_19_R3.CraftChunk.getHandle()'
        at com.bgsoftware.wildtools.nms.v1194.NMSWorld.refreshChunk(NMSWorld.java:132) ~[WildTools-2023.1.jar:?]
        at com.bgsoftware.wildtools.utils.world.WorldEditSession.lambda$apply$3(WorldEditSession.java:114) ~[WildTools-2023.1.jar:?]
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
        at com.bgsoftware.wildtools.utils.world.WorldEditSession.apply(WorldEditSession.java:107) ~[WildTools-2023.1.jar:?]
        at com.bgsoftware.wildtools.tools.WBuilderTool.onBlockInteract(WBuilderTool.java:106) ~[WildTools-2023.1.jar:?]
        at com.bgsoftware.wildtools.listeners.BlocksListener.onBlockInteract(BlocksListener.java:133) ~[WildTools-2023.1.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor62.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:git-Pufferfish-69]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.19.4.jar:git-Pufferfish-69]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.19.4.jar:git-Pufferfish-69]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:562) ~[pufferfish-1.19.4.jar:git-Pufferfish-69]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1959) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.19.4.jar:git-Pufferfish-69]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1344) ~[pufferfish-1.19.4.jar:git-Pufferfish-69]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[pufferfish-1.19.4.jar:git-Pufferfish-69]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1321) ~[pufferfish-1.19.4.jar:git-Pufferfish-69]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1314) ~[pufferfish-1.19.4.jar:git-Pufferfish-69]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1292) ~[pufferfish-1.19.4.jar:git-Pufferfish-69]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[pufferfish-1.19.4.jar:git-Pufferfish-69]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[pufferfish-1.19.4.jar:git-Pufferfish-69]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by OmerBenGera** [comment]
Update to latest dev build
