### ISSUE TITLE
Could not pass event BlockBreakEvent to WildTools v2023.2

### ISSUE THREAD

**Issue by byorage** [BG-Software-LLC/WildTools#161]
### Minecraft's Version

Version Paper 1.18.2

### Plugin's Version

Wildtools v2023.2
hopper plugin : https://www.spigotmc.org/resources/chunk-hopper-%E2%9C%94auto-sell-%E2%9C%94auto-kill-%E2%9C%94gui-support.79062/

### Describe the bug

the hammer so the "Trench Pickaxe" function does not work and sends me this error in the console:

[18:09:52 ERROR]: Could not pass event BlockBreakEvent to WildTools v2023.2
java.lang.NoClassDefFoundError: dev/warse/chunkhoppers/ChunkHoppers
        at com.bgsoftware.wildtools.hooks.DropsProvider_ChunkHoppers.getBlockDrops(DropsProvider_ChunkHoppers.java:18) ~[WildTools-2023.2.jar:?]
        at com.bgsoftware.wildtools.handlers.ProvidersHandler.getBlockDrops(ProvidersHandler.java:98) ~[WildTools-2023.2.jar:?]
        at com.bgsoftware.wildtools.utils.BukkitUtils.getBlockDrops(BukkitUtils.java:191) ~[WildTools-2023.2.jar:?]
        at com.bgsoftware.wildtools.utils.BukkitUtils.collectDropsFromTool(BukkitUtils.java:203) ~[WildTools-2023.2.jar:?]
        at com.bgsoftware.wildtools.utils.BukkitUtils.breakBlock(BukkitUtils.java:123) ~[WildTools-2023.2.jar:?]
        at com.bgsoftware.wildtools.tools.WCuboidTool.onBlockBreak(WCuboidTool.java:57) ~[WildTools-2023.2.jar:?]
        at com.bgsoftware.wildtools.listeners.BlocksListener.onBlockBreak(BlocksListener.java:71) ~[WildTools-2023.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor957.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:412) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:366) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:248) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1770) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:14) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.warse.chunkhoppers.ChunkHoppers
        ... 32 more

### To Reproduce

add just the plugin of chunk hopper and mine with a hammer

### Additional Information

error:

[18:09:52 ERROR]: Could not pass event BlockBreakEvent to WildTools v2023.2
java.lang.NoClassDefFoundError: dev/warse/chunkhoppers/ChunkHoppers
        at com.bgsoftware.wildtools.hooks.DropsProvider_ChunkHoppers.getBlockDrops(DropsProvider_ChunkHoppers.java:18) ~[WildTools-2023.2.jar:?]
        at com.bgsoftware.wildtools.handlers.ProvidersHandler.getBlockDrops(ProvidersHandler.java:98) ~[WildTools-2023.2.jar:?]
        at com.bgsoftware.wildtools.utils.BukkitUtils.getBlockDrops(BukkitUtils.java:191) ~[WildTools-2023.2.jar:?]
        at com.bgsoftware.wildtools.utils.BukkitUtils.collectDropsFromTool(BukkitUtils.java:203) ~[WildTools-2023.2.jar:?]
        at com.bgsoftware.wildtools.utils.BukkitUtils.breakBlock(BukkitUtils.java:123) ~[WildTools-2023.2.jar:?]
        at com.bgsoftware.wildtools.tools.WCuboidTool.onBlockBreak(WCuboidTool.java:57) ~[WildTools-2023.2.jar:?]
        at com.bgsoftware.wildtools.listeners.BlocksListener.onBlockBreak(BlocksListener.java:71) ~[WildTools-2023.2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor957.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-388]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:669) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyBlock(ServerPlayerGameMode.java:412) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.destroyAndAck(ServerPlayerGameMode.java:366) ~[?:?]
        at net.minecraft.server.level.ServerPlayerGameMode.handleBlockBreakAction(ServerPlayerGameMode.java:248) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handlePlayerAction(ServerGamePacketListenerImpl.java:1770) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.handle(ServerboundPlayerActionPacket.java:34) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundPlayerActionPacket.a(ServerboundPlayerActionPacket.java:14) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1400) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1377) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1370) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1504) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.18.2.jar:git-Paper-388]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.warse.chunkhoppers.ChunkHoppers
        ... 32 more

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
