### ISSUE TITLE
WildTools - Builder wand

### ISSUE THREAD

**Issue by Aides123** [BG-Software-LLC/WildTools#193]
### Minecraft's Version

This server is running Pufferfish version git-Pufferfish-49 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 852ea89 on HEAD)

### Plugin's Version

#37

### Describe the bug

The builder's wand allows you to copy water through half slabs flooded with water.

### To Reproduce

In the video you can see how it looks specifically and what needs to be done.
https://github.com/BG-Software-LLC/WildTools/assets/23367220/c1fedf5f-d1be-4611-b3d1-ef010baad52e

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by Aides123** [comment]
it works thanks

**Comment by Aides123** [comment]
[05:01:38] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to WildTools v2024.1-b39
java.lang.IllegalArgumentException: Cannot get property BlockStateBoolean{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:dark_oak_planks}
	at net.minecraft.world.level.block.state.StateHolder.getValue(StateHolder.java:96) ~[?:?]
	at com.bgsoftware.wildtools.nms.v1_20_3.NMSWorldImpl.getCombinedId(NMSWorldImpl.java:142) ~[WildTools-2024.1-b39.jar:?]
	at com.bgsoftware.wildtools.utils.world.WorldEditSession.setType(WorldEditSession.java:45) ~[WildTools-2024.1-b39.jar:?]
	at com.bgsoftware.wildtools.utils.BukkitUtils.placeBlock(BukkitUtils.java:183) ~[WildTools-2024.1-b39.jar:?]
	at com.bgsoftware.wildtools.tools.WBuilderTool.onBlockInteract(WBuilderTool.java:102) ~[WildTools-2024.1-b39.jar:?]
	at com.bgsoftware.wildtools.listeners.BlocksListener.onBlockInteract(BlocksListener.java:132) ~[WildTools-2024.1-b39.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor681.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:git-Pufferfish-51]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1936) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1472) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1449) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1350) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1239) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[05:01:39] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to WildTools v2024.1-b39
java.lang.IllegalArgumentException: Cannot get property BlockStateBoolean{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:dark_oak_planks}
	at net.minecraft.world.level.block.state.StateHolder.getValue(StateHolder.java:96) ~[?:?]
	at com.bgsoftware.wildtools.nms.v1_20_3.NMSWorldImpl.getCombinedId(NMSWorldImpl.java:142) ~[WildTools-2024.1-b39.jar:?]
	at com.bgsoftware.wildtools.utils.world.WorldEditSession.setType(WorldEditSession.java:45) ~[WildTools-2024.1-b39.jar:?]
	at com.bgsoftware.wildtools.utils.BukkitUtils.placeBlock(BukkitUtils.java:183) ~[WildTools-2024.1-b39.jar:?]
	at com.bgsoftware.wildtools.tools.WBuilderTool.onBlockInteract(WBuilderTool.java:102) ~[WildTools-2024.1-b39.jar:?]
	at com.bgsoftware.wildtools.listeners.BlocksListener.onBlockInteract(BlocksListener.java:132) ~[WildTools-2024.1-b39.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor681.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:git-Pufferfish-51]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1936) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1472) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1449) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:112) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1564) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[05:01:40] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to WildTools v2024.1-b39
java.lang.IllegalArgumentException: Cannot get property BlockStateBoolean{name=waterlogged, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{minecraft:dark_oak_planks}
	at net.minecraft.world.level.block.state.StateHolder.getValue(StateHolder.java:96) ~[?:?]
	at com.bgsoftware.wildtools.nms.v1_20_3.NMSWorldImpl.getCombinedId(NMSWorldImpl.java:142) ~[WildTools-2024.1-b39.jar:?]
	at com.bgsoftware.wildtools.utils.world.WorldEditSession.setType(WorldEditSession.java:45) ~[WildTools-2024.1-b39.jar:?]
	at com.bgsoftware.wildtools.utils.BukkitUtils.placeBlock(BukkitUtils.java:183) ~[WildTools-2024.1-b39.jar:?]
	at com.bgsoftware.wildtools.tools.WBuilderTool.onBlockInteract(WBuilderTool.java:102) ~[WildTools-2024.1-b39.jar:?]
	at com.bgsoftware.wildtools.listeners.BlocksListener.onBlockInteract(BlocksListener.java:132) ~[WildTools-2024.1-b39.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor681.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:git-Pufferfish-51]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[pufferfish-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1936) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1472) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1449) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1372) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:112) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1564) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[pufferfish-1.20.4.jar:git-Pufferfish-51]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by Aides123** [comment]
ah already closed, I will create a new one
