### ISSUE TITLE
When I break the ores I get nothing with the couboid tools

### ISSUE THREAD

**Issue by iJuju68** [BG-Software-LLC/WildTools#201]
### Minecraft's Version

1.8/JAVA 17

### Plugin's Version

2024.1-b45 and tested in 2024.1

### Describe the bug

When I break a block in the whitelist with the cuboid tool : 
I have the error in the console : 
[13:57:27 ERROR]: Could not pass event BlockBreakEvent to WildTools v2024.1-b45
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.a(PlayerInteractManager.java:215) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:640) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:40) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockDig.a(SourceFile:10) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.bgsoftware.wildtools.hooks.StackedItemProvider.dropItem(org.bukkit.Location, org.bukkit.inventory.ItemStack, int)" because the return value of "com.bgsoftware.wildtools.handlers.ProvidersHandler.getStackedItemProvider()" is null
        at com.bgsoftware.wildtools.utils.world.WorldEditSession.lambda$apply$3(WorldEditSession.java:128) ~[?:?]
        at java.util.Map.forEach(Map.java:713) ~[?:?]
        at com.bgsoftware.wildtools.utils.world.WorldEditSession.apply(WorldEditSession.java:127) ~[?:?]
        at com.bgsoftware.wildtools.tools.WCuboidTool.onBlockBreak(WCuboidTool.java:69) ~[?:?]
        at com.bgsoftware.wildtools.listeners.BlocksListener.onBlockBreak(BlocksListener.java:72) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 18 more

### To Reproduce

Use the same version.

**Comment by OmerBenGera** [comment]
Send me your entire session logs via pastebin

**Comment by iJuju68** [comment]
https://pastebin.com/t8xdCS58

**Comment by OmerBenGera** [comment]
> https://pastebin.com/t8xdCS58

Send me the entire latest.log file

**Comment by iJuju68** [comment]
This is le latest.log : https://pastebin.com/6BRF1Mpt

**Comment by OmerBenGera** [comment]
Check out latest dev build, let me know if it is fixed

**Comment by OmerBenGera** [comment]
I am closing this for now
If the issue still occurs, let me know
