### ISSUE TITLE
Harvester Hoe durability not running out

### ISSUE THREAD

**Issue by kamber5** [BG-Software-LLC/WildTools#207]
### Minecraft's Version

Paper version 1.21.1-119-master@7cd4f2c

### Plugin's Version

2024.3

### Describe the bug

[11:25:41 ERROR]: Could not pass event PlayerInteractEvent to WildTools v2024.3
java.lang.NoSuchMethodError: 'void org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerItemBreakEvent(net.minecraft.world.entity.player.Player, net.minecraft.world.item.ItemStack)'
        at WildTools-2024.3.jar/com.bgsoftware.wildtools.nms.v1_21.tool.ToolItemStackImpl.breakTool(ToolItemStackImpl.java:79) ~[WildTools-2024.3.jar:?]
        at WildTools-2024.3.jar/com.bgsoftware.wildtools.utils.items.ItemUtils.reduceDurability(ItemUtils.java:127) ~[WildTools-2024.3.jar:?]
        at WildTools-2024.3.jar/com.bgsoftware.wildtools.tools.WTool.reduceDurablility(WTool.java:453) ~[WildTools-2024.3.jar:?]
        at WildTools-2024.3.jar/com.bgsoftware.wildtools.tools.WHarvesterTool.handleUse(WHarvesterTool.java:279) ~[WildTools-2024.3.jar:?]
        at WildTools-2024.3.jar/com.bgsoftware.wildtools.tools.WHarvesterTool.onBlockInteract(WHarvesterTool.java:134) ~[WildTools-2024.3.jar:?]
        at WildTools-2024.3.jar/com.bgsoftware.wildtools.listeners.BlocksListener.onBlockInteract(BlocksListener.java:132) ~[WildTools-2024.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor662.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:604) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1942) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:11) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1535) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1512) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1505) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1464) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1471) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1316) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-119-7cd4f2c]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### To Reproduce

Use a Harv Hoe with durability and the hoe wont break at all. When the hoe is at 1 it wont go down and wont break.
![{A844AE8F-8224-4BEA-8298-5F741254E0FE}](https://github.com/user-attachments/assets/68f8eca8-d8cc-4c57-b373-3e1546457bcc)

  harvester_hoe1:
    tool-mode: HARVESTER
    radius: 2
    auto-collect: true
    type: DIAMOND_HOE
    uses: 200
    name: '&f --{ &d&lHarvester Hoe &f}-- '
    lore:
    - '&8&m---------------------------------------'
    - '&7 Kliknite na blok da berete, ponovo posadite'
    - '&7 semena i pretvoriti dirt u farmlands.'
    - '&7'
    - '&d&l Uses:'
    - '&f   {}'
    - '&f'
    - '&8&m---------------------------------------'

**Comment by OmerBenGera** [comment]
I cannot replicate the issue myself.
Using latest dev build of WildTools, Paper version `1.21.1-123-master@aebbdc9`

**Comment by kamber5** [comment]
Issue seems to be with the last stable build.
I have tested now with latest dev build that you released today and it does not have this problem.

**Comment by OmerBenGera** [comment]
Great.
Closing this for now, and I will post a new stable build soon
