### ISSUE TITLE
Compatibility with McMMO

### ISSUE THREAD

**Issue by Patrity** [BG-Software-LLC/WildTools#53]
**Minecraft's Version**
Airplane-4a22184

**Plugin's Version**: -
2.10.4

**Describe the bug**
Builders wands place blocks whether you have the item or not, once broken they are still registered, creating "ghost blocks" and duping the items.

**To Reproduce**
With McMMO installed, use the builder wand as intended.

**Additional information**
```[23:00:23 ERROR]: Could not pass event PlayerInteractEvent to WildTools v2.10.4
java.lang.NoSuchMethodError: 'com.gmail.nossr50.util.blockmeta.chunkmeta.ChunkManager com.gmail.nossr50.mcMMO.getPlaceStore()'
        at com.bgsoftware.wildtools.hooks.McMMOHook.markAsPlaced(McMMOHook.java:16) ~[?:?]
        at com.bgsoftware.wildtools.utils.blocks.BlocksController.updateSession(BlocksController.java:63) ~[?:?]
        at com.bgsoftware.wildtools.objects.tools.WBuilderTool.onBlockInteract(WBuilderTool.java:114) ~[?:?]
        at com.bgsoftware.wildtools.listeners.BlocksListener.onBlockInteract(BlocksListener.java:135) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1128.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:545) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:532) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1787) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:32) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:10) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1321) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1314) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1290) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1134) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:290) ~[patched_1.16.5.jar:git-Airplane-"4a22184"]
        at java.lang.Thread.run(Thread.java:834) [?:?]```

**Comment by OmerBenGera** [comment]
What version of mcMMO are you using?

**Comment by Patrity** [comment]
> What version of mcMMO are you using?

2.1.181

**Comment by OmerBenGera** [comment]
Mind sending me a copy of it via discord?
If so, send me your discord and I'll open a private ticket for you

**Comment by Patrity** [comment]
> Mind sending me a copy of it via discord?
> If so, send me your discord and I'll open a private ticket for you

Patrity#0001

**Comment by OmerBenGera** [comment]
It works fine for me, maybe it's already fixed in a dev build
Check out the latest dev build on https://bg-software.com/wildtools/ and let me know if it works

**Comment by Patrity** [comment]
Confirmed fixed.
