### ISSUE TITLE
Mcmmo hook not working properly

### ISSUE THREAD

**Issue by WolverStones** [BG-Software-LLC/WildTools#88]
### Minecraft's Version

[18:33:25 INFO]: This server is running Purpur version git-Purpur-1493 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 695f09c on HEAD)
[18:33:25 INFO]: You are running the latest version
[18:33:25 INFO]: Previous version: git-Purpur-1454 (MC: 1.18.1)
Príkaz:

### Plugin's Version

[18:33:41 INFO]: WildTools version 2.11.3.46
[18:33:41 INFO]: Configurable trench picks, tray picks, sell-wands, harvester-hoes and more!
[18:33:41 INFO]: Website: https://bg-software.com/
[18:33:41 INFO]: Author: Ome_R

### Describe the bug

When using builderwand, blocks are not subtracted, nor is the use of wand.

Error in console:
```
[18:30:06 ERROR]: Could not pass event PlayerInteractEvent to WildTools v2.11.3.46
java.lang.NullPointerException: Cannot invoke "com.bgsoftware.common.reflection.ReflectMethod.invoke(Object, Object[])" because "com.bgsoftware.wildtools.hooks.McMMOHook.MCMMO_PLACESTORE_SET" is null
at com.bgsoftware.wildtools.hooks.McMMOHook.recordBlockChange(McMMOHook.java:49) ~[WildTools-2.11.3-b46.jar:?]
at com.bgsoftware.wildtools.handlers.ProvidersHandler.lambda$notifyToolBlockListeners$3(ProvidersHandler.java:190) ~[WildTools-2.11.3-b46.jar:?]
at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
at com.bgsoftware.wildtools.handlers.ProvidersHandler.notifyToolBlockListeners(ProvidersHandler.java:190) ~[WildTools-2.11.3-b46.jar:?]
at com.bgsoftware.wildtools.utils.blocks.BlocksController.updateSession(BlocksController.java:59) ~[WildTools-2.11.3-b46.jar:?]
at com.bgsoftware.wildtools.objects.tools.WBuilderTool.onBlockInteract(WBuilderTool.java:114) ~[WildTools-2.11.3-b46.jar:?]
at com.bgsoftware.wildtools.listeners.BlocksListener.onBlockInteract(BlocksListener.java:135) ~[WildTools-2.11.3-b46.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor492.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:git-Purpur-1493]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:543) ~[purpur-1.18.1.jar:git-Purpur-1493]
at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:542) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1911) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:56) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.1.jar:git-Purpur-1493]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1440) ~[purpur-1.18.1.jar:git-Purpur-1493]
at net.minecraft.server.MinecraftServer.c(MinecraftServer.java:189) ~[purpur-1.18.1.jar:git-Purpur-1493]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:122) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1418) ~[purpur-1.18.1.jar:git-Purpur-1493]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1411) ~[purpur-1.18.1.jar:git-Purpur-1493]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:132) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1389) ~[purpur-1.18.1.jar:git-Purpur-1493]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1295) ~[purpur-1.18.1.jar:git-Purpur-1493]
at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:322) ~[purpur-1.18.1.jar:git-Purpur-1493]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### To Reproduce

When using Wildtools and the Mcmmo plugin, the use of the Builderwand item is not subtracted, nor are the blocks from inv. 

Preview video: https://youtu.be/0XUv7kqRsuU

### Additional Information

MCMMO version: 2.1.207

Mcmmo can be downloaded here: https://github.com/mcMMO-Dev/mcMMO

**Comment by OmerBenGera** [comment]
Do you mind sending me the mcmmo jar that you use?
I will open a ticket for you so you can do that.

**Comment by WolverStones** [comment]
> Do you mind sending me the mcmmo jar that you use? I will open a ticket for you so you can do that.

Ok, but I can't open the ticket my discord ID WolverStone#0298

**Comment by OmerBenGera** [comment]
Fixed in latest dev build
